name = "Gold Not Old"
author = "Cjnator38"
version = "1.0-pre5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95b3f7715654459b1f60e364c898d5c5e5335b8cc13f83f69bf932990dfa15f4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
