name = "Gold Not Old"
author = "Cjnator38"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f1a9f0a95170189d3c48b1540399956eeabe0ebc02e8af46e2d1a5e0b1a786e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
